package com.crbt.api.services.domain;
// Generated 22 Dec, 2020 11:29:55 AM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FavoritesId generated by hbm2java
 */
@Embeddable
public class FavoritesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7093961327612135512L;
	private Subscriber subscriberId;
	private TopContent topContentId;

	public FavoritesId() {
	}



	public FavoritesId(Subscriber subscriberId, TopContent topContentId) {
		this.subscriberId = subscriberId;
		this.topContentId = topContentId;
	}



	//@Column(name = "subscriber_id", nullable = false)
	public Subscriber getSubscriberId() {
		return this.subscriberId;
	}

	public void setSubscriberId(Subscriber subscriberId) {
		this.subscriberId = subscriberId;
	}

	//@Column(name = "top_content_id", nullable = false)
	public TopContent getTopContentId() {
		return this.topContentId;
	}

	public void setTopContentId(TopContent topContentId) {
		this.topContentId = topContentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FavoritesId))
			return false;
		FavoritesId castOther = (FavoritesId) other;

		return (this.getSubscriberId().getId() == castOther.getSubscriberId().getId())
				&& (this.getTopContentId().getId() == castOther.getTopContentId().getId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSubscriberId().getId();
		result = 37 * result + this.getTopContentId().getId();
		return result;
	}

}
