package com.crbt.api.services.domain;
// Generated 22 Dec, 2020 11:29:55 AM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Favorites generated by hbm2java
 */
@Entity
@Table(name = "favorites", catalog = "rbtlibyana")
@IdClass(FavoritesId.class)
public class Favorites implements java.io.Serializable {

	//private FavoritesId id;
	//private TopContent topContent;
	
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 950019471558185894L;

	@Id
	@OneToOne
	@JoinColumn(name="top_content_id")
	private TopContent topContentId;
	
	@Id
	@OneToOne
	@JoinColumn(name="subscriber_id")
	private Subscriber subscriberId;
	
	
	/*private Date createDate;*/

	public Favorites() {
	}

	

	


public Favorites(TopContent topContentId, Subscriber subscriberId) {
		this.topContentId = topContentId;
		this.subscriberId = subscriberId;
	}






/*	@OneToOne
	@JoinColumn(name="subscriber_id")
	private Subscriber subscriber_id;
	
	@OneToOne
	@JoinColumn(name="top_content_id")
	private TopContent top_content_id;
	
	*/
	

	/*@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createDate", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}*/






	public TopContent getTopContentId() {
		return topContentId;
	}






	public void setTopContentId(TopContent topContentId) {
		this.topContentId = topContentId;
	}






	public Subscriber getSubscriberId() {
		return subscriberId;
	}






	public void setSubscriberId(Subscriber subscriberId) {
		this.subscriberId = subscriberId;
	}




	
	
}
