package com.crbt.api.services.domain;
// Generated 22 Dec, 2020 10:19:10 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * TrackRating generated by hbm2java
 */
@Entity
@Table(name = "track_rating", catalog = "rbtlibyana")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class TrackRating implements java.io.Serializable {

	private Integer id;
	private TopContent topContent;
	private Integer rating;
	private String remarks;
	private Date createDate;

	public TrackRating() {
	}

	public TrackRating(TopContent topContent, Integer rating, String remarks, Date createDate) {
		this.topContent = topContent;
		this.rating = rating;
		this.remarks = remarks;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "top_content_id")
	public TopContent getTopContent() {
		return this.topContent;
	}

	public void setTopContent(TopContent topContent) {
		this.topContent = topContent;
	}

	@Column(name = "rating")
	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

	@Column(name = "remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
